[build]
  command = "npx --yes tailwindcss -c tailwind.config.js --content './*.html,./{blog,bundle,free,guides,products,store,toolkit}/**/*.html,./**/*.md,./**/*.js' -i ./css/tailwind.input.css -o ./css/site.css --minify"
  publish = "."

[build.environment]
  NODE_VERSION = "20"
