[build]
  command = "echo '--- CONFIG ---'; sed -n '1,80p' tailwind.config.js; echo; npx --yes tailwindcss -c tailwind.config.js -i ./css/tailwind.input.css -o ./css/site.css --minify"
  publish = "."
