name: Site Monitor

on:
  schedule:
    - cron: "5 * * * *"        # runs hourly at :05 (UTC)
  workflow_dispatch: {}         # allows manual run from Actions tab

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Homepage
        id: home
        run: |
          set -e
          URL="https://mikeguides.co"
          STATUS=$(curl -s -o /tmp/home.html -w "%{http_code}" "$URL")
          if [ "$STATUS" -ne 200 ]; then
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "Homepage HTTP $STATUS" > /tmp/home_err.txt
            exit 0
          fi
          if ! grep -q "MikeGuides — Interactive HTML Guides" /tmp/home.html; then
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "Homepage missing brand keyword" > /tmp/home_err.txt
            exit 0
          fi
          if ! grep -q "WEEK1000 Bundle — Save \$100" /tmp/home.html; then
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "Homepage missing WEEK1000 promo block" > /tmp/home_err.txt
            exit 0
          fi
          echo "status=ok" >> $GITHUB_OUTPUT

      - name: Check Toolkit
        id: toolkit
        run: |
          set -e
          URL="https://mikeguides.co/toolkit/"
          STATUS=$(curl -s -o /tmp/toolkit.html -w "%{http_code}" "$URL")
          if [ "$STATUS" -ne 200 ]; then
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "Toolkit HTTP $STATUS" > /tmp/toolkit_err.txt
            exit 0
          fi
          if ! grep -q "AI Marketing Toolkit" /tmp/toolkit.html; then
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "Toolkit page missing keyword" > /tmp/toolkit_err.txt
            exit 0
          fi
          echo "status=ok" >> $GITHUB_OUTPUT

      - name: Fail if anything broke
        if: steps.home.outputs.status == 'fail' || steps.toolkit.outputs.status == 'fail'
        run: |
          echo "Site check failed."
          exit 1

      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 Site Monitor: Check failed at ${{ github.run_id }}"
          content-filepath: |
            $( [ -f /tmp/home_err.txt ] && echo /tmp/home_err.txt )
            $( [ -f /tmp/toolkit_err.txt ] && echo /tmp/toolkit_err.txt )
          labels: |
            incident
            site-monitor
