name: MikeGuides Utilities

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose a task"
        required: true
        type: choice
        default: "Just log success"
        options:
          - "Just log success"
          - "Trigger Netlify build hook"
          - "Purge Netlify cache and redeploy"
          - "Bust image cache (purge CDN)"
      confirm:
        description: "Check to confirm you really want to run this task"
        required: true
        type: boolean
        default: false

permissions:
  contents: read

      - name: Bust image cache (purge CDN)
        if: ${{ github.event.inputs.task == 'Bust image cache (purge CDN)' }}
        env:
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          if [ -z "$NETLIFY_API_TOKEN" ] || [ -z "$NETLIFY_SITE_ID" ]; then
            echo "❌ NETLIFY_API_TOKEN or NETLIFY_SITE_ID not set."
            exit 1
          fi

          echo "🧨 Requesting purge for entire site $NETLIFY_SITE_ID"
          # Purge entire site cache. If you ever want to purge SPECIFIC URLs, see the commented block below.
          http_code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${NETLIFY_API_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://api.netlify.com/api/v1/sites/${NETLIFY_SITE_ID}/purge")

          echo "Netlify response (HTTP $http_code):"
          cat /tmp/resp.json | sed 's/.*/  &/'

          if [ "$http_code" -ge 400 ]; then
            echo "❌ Purge failed."
            exit 1
          fi
          echo "✅ CDN cache purge requested."

          # --- Purge specific URLs (optional) ---
          # To purge only certain files, use this instead (URLs must be on your site domain):
          # curl -sS -X POST \
          #   -H "Authorization: Bearer ${NETLIFY_API_TOKEN}" \
          #   -H "Content-Type: application/json" \
          #   --data "{\"urls\":[\"https://mikeguides.co/assets/images/products/card_hallow_aimarketingtoolkit.v20251023a.960x960.jpg\"]}" \
          #   "https://api.netlify.com/api/v1/sites/${NETLIFY_SITE_ID}/purge"
